from collections.abc import AsyncIterator, Awaitable, Callable

class TelegramClient:
    flood_sleep_threshold: int
    def __init__(
        self,
        session: str,
        api_id: int,
        api_hash: str,
        *,
        device_model: str,
        system_version: str,
        app_version: str,
    ) -> None: ...
    async def __call__(self, request: object, ordered: bool = False) -> object: ...
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def is_user_authorized(self) -> bool: ...
    async def get_me(self) -> object: ...
    async def send_code_request(self, phone: str) -> object: ...
    async def sign_in(
        self,
        *,
        phone: str | None = None,
        code: str | None = None,
        password: str | None = None,
    ) -> object: ...
    async def qr_login(self) -> object: ...
    async def log_out(self) -> None: ...
    async def get_entity(self, value: object) -> object: ...
    async def get_input_entity(self, value: object) -> object: ...
    def iter_dialogs(self, *, limit: int) -> AsyncIterator[object]: ...
    def iter_messages(
        self,
        entity: object,
        *,
        min_id: int | None = None,
        reverse: bool = False,
        limit: int,
        search: str | None = None,
    ) -> AsyncIterator[object]: ...
    def on(
        self,
        event: object,
    ) -> Callable[[Callable[[object], Awaitable[None]]], Callable[[object], Awaitable[None]]]: ...
    async def run_until_disconnected(self) -> None: ...
    async def send_message(self, entity: object, message: str, *, reply_to: int | None) -> object: ...
    async def send_file(self, entity: object, *, file: str, caption: str | None, reply_to: int | None) -> object: ...
    async def upload_file(self, path: str) -> object: ...
