class RPCError(Exception): ...

class FloodWaitError(RPCError):
    seconds: int

class PasswordHashInvalidError(RPCError): ...
class PhoneCodeExpiredError(RPCError): ...
class PhoneCodeInvalidError(RPCError): ...
class SessionPasswordNeededError(RPCError): ...
